[app]
name = "diego-jauregui-photography"
primary_region = "lax"

[build]

[env]
  DATA_DIR = "/data"
  NODE_ENV = "production"

[mounts]
  source = "photo_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
